# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20151126_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarduser',
            options={},
        ),
    ]
