# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20151202_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=256, unique=True)),
                ('test', models.CharField(max_length=256)),
                ('yes', models.FloatField(null=True)),
                ('no', models.FloatField(null=True)),
                ('not_reporting', models.FloatField(null=True)),
            ],
        ),
    ]
