# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_cycletestscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletestscore',
            name='formulation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
