# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cycletestscore_formulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleFormulationTestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=256, unique=True)),
                ('test', models.CharField(max_length=256)),
                ('yes', models.FloatField(null=True)),
                ('no', models.FloatField(null=True)),
                ('not_reporting', models.FloatField(null=True)),
                ('formulation', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cycletestscore',
            name='formulation',
        ),
    ]
