# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20151204_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleformulationtestscore',
            name='cycle',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='cycleformulationtestscore',
            unique_together=set([('cycle', 'formulation')]),
        ),
    ]
