# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 18:09
from __future__ import unicode_literals

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_admin_user(apps, schema_editor):
    DashboardUser = apps.get_registered_model("dashboard", "DashboardUser")
    user, created = DashboardUser.objects.get_or_create(email="admin@a.com", password=make_password("admin"), access_level="MOH CENTRAL")
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0008_delete_cycleformulationscore'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
