# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20160424_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='pmtct_consumption',
        ),
    ]
