# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20151208_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletestscore',
            name='cycle',
            field=models.CharField(max_length=256),
        ),
    ]
