# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0011_auto_20171023_0715")]

    operations = [
        migrations.RenameField(
            model_name="consumption",
            old_name="combined_consumption",
            new_name="consumption",
        )
    ]
