# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20151208_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitycyclerecordscore',
            name='formulation',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='facilitycyclerecord',
            unique_together=set([('cycle', 'facility')]),
        ),
        migrations.AlterUniqueTogether(
            name='facilitycyclerecordscore',
            unique_together=set([('facility_cycle', 'formulation', 'test')]),
        ),
    ]
