# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0012_auto_20171023_0720")]

    operations = [
        migrations.RenameField(
            model_name="score", old_name="nnrtiCurrentAdults", new_name="nnrtiAdults"
        ),
        migrations.RemoveField(model_name="score", name="nnrtiNewAdults"),
    ]
