# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20151211_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='access_level',
            field=models.CharField(choices=[(b'Facility', b'Facility'), (b'Warehouse', b'Warehouse'), (b'District', b'District'), (b'IP', b'IP')], default='IP', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilitycyclerecordscore',
            name='facility_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='dashboard.FacilityCycleRecord'),
        ),
    ]
