# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20151216_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='access_level',
            field=models.CharField(choices=[(b'Warehouse', b'Warehouse'), (b'District', b'District'), (b'IP', b'IP'), (b'MOH CENTRAL', b'MOH CENTRAL')], max_length=50),
        ),
    ]
