# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-29 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0014_consumption_days_out_of_stock")]

    operations = [migrations.RemoveField(model_name="score", name="nnrtiNewPaed")]
