# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20151216_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cycle', models.CharField(max_length=256)),
                ('test', models.CharField(max_length=256)),
                ('district', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=256)),
                ('warehouse', models.CharField(max_length=256)),
                ('formulation', models.CharField(max_length=256, null=True)),
                ('nnrtiNewPaed', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('stablePatientVolumes', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('REPORTING', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('consumptionAndPatients', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('nnrtiCurrentPaed', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('warehouseFulfilment', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('differentOrdersOverTime', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('closingBalanceMatchesOpeningBalance', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('WEB_BASED', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('OrderFormFreeOfGaps', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('MULTIPLE_ORDERS', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('nnrtiNewAdults', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('orderFormFreeOfNegativeNumbers', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('nnrtiCurrentAdults', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('stableConsumption', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('guidelineAdherenceAdultlL', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('guidelineAdherenceAdult2L', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
                ('guidelineAdherencePaed1L', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO'), (b'NOT_REPORTING', b'NOT_REPORTING')], max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='FacilityConsumptionRecord',
            new_name='Consumption',
        ),
        migrations.RenameModel(
            old_name='FacilityCycleRecord',
            new_name='Cycle',
        ),
        migrations.RenameModel(
            old_name='CycleFormulationTestScore',
            new_name='CycleFormulationScore',
        ),
        migrations.RenameModel(
            old_name='CycleTestScore',
            new_name='CycleScore',
        ),
        migrations.AlterUniqueTogether(
            name='facilitycyclerecordscore',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='facilitycyclerecordscore',
            name='facility_cycle',
        ),
        migrations.DeleteModel(
            name='FacilityCycleRecordScore',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('name', 'cycle', 'test', 'formulation')]),
        ),
    ]
