# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-29 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_score_nnrtinewpaed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='nnrtiCurrentPaed',
            new_name='nnrtiPaed',
        ),
    ]
