# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20151218_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='formulation',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='cycle',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
