# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20151221_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultpatientsrecord',
            name='facility_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='dashboard.Cycle'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='facility_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption', to='dashboard.Cycle'),
        ),
        migrations.AlterField(
            model_name='paedpatientsrecord',
            name='facility_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pds', to='dashboard.Cycle'),
        ),
    ]
