# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20151221_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='guidelineAdherenceAdultlL',
            new_name='guidelineAdherenceAdult1L',
        ),
    ]
