# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 19:51
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0019_auto_20151223_0041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
                name='score',
                unique_together=set([('name', 'cycle', 'district')]),
        ),
        migrations.RemoveField(
                model_name='score',
                name='formulation',
        ),
        migrations.RemoveField(
                model_name='score',
                name='test',
        ),
        migrations.AlterField(
                model_name='score',
                name='closingBalanceMatchesOpeningBalance',
                field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
                model_name='score',
                name='consumptionAndPatients',
                field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
                model_name='score',
                name='differentOrdersOverTime',
                field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
                model_name='score',
                name='orderFormFreeOfNegativeNumbers',
                field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
                model_name='score',
                name='stableConsumption',
                field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
                model_name='score',
                name='stablePatientVolumes',
                field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
                model_name='score',
                name='warehouseFulfilment',
                field=jsonfield.fields.JSONField(),
        ),
    ]
