# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 21:26
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20151223_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='MULTIPLE_ORDERS',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='OrderFormFreeOfGaps',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='REPORTING',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='WEB_BASED',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='guidelineAdherenceAdult1L',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='guidelineAdherenceAdult2L',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='guidelineAdherencePaed1L',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='nnrtiCurrentAdults',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='nnrtiCurrentPaed',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='nnrtiNewAdults',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='nnrtiNewPaed',
            field=jsonfield.fields.JSONField(),
        ),
    ]
