# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0021_auto_20171107_2010")]

    operations = [
        migrations.AlterField(
            model_name="dhis2standardreport",
            name="partner",
            field=models.CharField(
                choices=[(b"MAUL", b"MAUL"), (b"JMS", b"JMS"), (b"NMS", b"NMS")],
                max_length=50,
            ),
        )
    ]
