# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-07 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20171107_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dhis2standardreport',
            old_name='partner',
            new_name='warehouse',
        ),
    ]
