# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20151224_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='total_quantity_to_be_ordered',
        ),
    ]
