# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-12 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20171107_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='months_of_stock_of_hand',
            new_name='months_of_stock_on_hand',
        ),
    ]
