# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-26 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20171112_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adultpatientsrecord',
            options={'verbose_name_plural': 'Adult Patient Records'},
        ),
        migrations.AlterModelOptions(
            name='consumption',
            options={'verbose_name_plural': 'Consumption Records'},
        ),
        migrations.AlterModelOptions(
            name='dashboarduser',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='dhis2standardreport',
            options={'verbose_name_plural': 'DHIS2 Standard Reports'},
        ),
        migrations.AlterModelOptions(
            name='multipleorderfacility',
            options={'verbose_name_plural': 'Facilities with Multiple Orders'},
        ),
        migrations.AlterModelOptions(
            name='paedpatientsrecord',
            options={'verbose_name_plural': 'Paed Patient Records'},
        ),
    ]
