# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-26 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20171127_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('definition', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Facility Test',
            },
        ),
    ]
