# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-26 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0026_facilitytest")]

    operations = [
        migrations.AlterModelOptions(
            name="facilitytest", options={"verbose_name_plural": "Facility Tests"}
        ),
        migrations.AddField(
            model_name="facilitytest",
            name="short_description",
            field=models.TextField(default="short description here"),
            preserve_default=False,
        ),
    ]
