# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-27 07:37
from __future__ import unicode_literals

import dashboard.widget
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20171127_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitytest',
            name='definition',
            field=dashboard.widget.TestDefinitionField(),
        ),
    ]
