# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-02 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0030_auto_20171127_1037")]

    operations = [migrations.RemoveField(model_name="facilitytest", name="test_type")]
