# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-10 22:55
from __future__ import unicode_literals

import jsonfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_facilitytest_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracingFormulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('formulations', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Tracing Formulations',
            },
        ),
    ]
