# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-10 22:55
from __future__ import unicode_literals

from django.db import migrations

CONSUMPTION = "Consumption"

PATIENTS = "Patients"

MODEL = "model"

FORMULATIONS = "formulations"

NAME = "name"

F3_PATIENT_QUERY = ["ABC/3TC/EFV", "AZT/3TC/EFV"]

F2_PATIENT_QUERY = ["ABC/3TC/LPV/r", "ABC/3TC/EFV", "ABC/3TC/NVP"]
F3 = "EFV200 (Paed)"
F2 = "ABC/3TC (Paed)"
F1 = "TDF/3TC/EFV (Adult)"
F1_PATIENT_QUERY = ["TDF/3TC/EFV (PMTCT)", "TDF/3TC/EFV (ADULT)"]
F1_QUERY = ["Tenofovir/Lamivudine/Efavirenz (TDF/3TC/EFV) 300mg/300mg/600mg[Pack 30]"]
F3_QUERY = ["Efavirenz (EFV) 200mg [Pack 90]"]
F2_QUERY = ["Abacavir/Lamivudine (ABC/3TC) 60mg/30mg [Pack 60]"]


def add_default_tracers(apps, schema_editor):
    model = apps.get_registered_model("dashboard", "TracingFormulations")
    tracers = [
        {NAME: F1, FORMULATIONS: F1_PATIENT_QUERY, MODEL: PATIENTS},
        {NAME: F2, FORMULATIONS: F2_PATIENT_QUERY, MODEL: PATIENTS},
        {NAME: F3, FORMULATIONS: F3_PATIENT_QUERY, MODEL: PATIENTS},
        {NAME: F1, FORMULATIONS: F1_QUERY, MODEL: CONSUMPTION},
        {NAME: F2, FORMULATIONS: F2_QUERY, MODEL: CONSUMPTION},
        {NAME: F3, FORMULATIONS: F3_QUERY, MODEL: CONSUMPTION},
    ]
    for tracer in tracers:
        model_obj, created = model.objects.get_or_create(**tracer)
        model_obj.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("dashboard", "0032_tracingformulations")]

    operations = [migrations.RunPython(add_default_tracers, reverse)]
