# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-17 05:20
from __future__ import unicode_literals

from django.db import migrations


def create_default_tests(apps, schema_editor):
    pass


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("dashboard", "0033_auto_20171211_0155")]

    operations = [migrations.RunPython(create_default_tests, reverse)]
