# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-25 04:24
from __future__ import unicode_literals

from django.db import migrations, models


def set_order(apps, schema_editor):
    model = apps.get_registered_model("dashboard", "FacilityTest")
    count = 1
    for test in model.objects.all():
        test.order = count
        test.save()
        count += 1


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0035_auto_20180125_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytest',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(set_order, reverse)
    ]
