# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0036_facilitytest_order")]

    operations = [
        migrations.AlterModelOptions(
            name="facilitytest",
            options={"ordering": ("order",), "verbose_name_plural": "Facility Tests"},
        ),
        migrations.AddField(
            model_name="facilitytest",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
