# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-24 04:06
from __future__ import unicode_literals

from django.db import migrations
from pydash import slugify


def update_slugs(apps, schema_editor):
    model = apps.get_registered_model("dashboard", "TracingFormulations")
    formulations = model.objects.all()
    for formulation in formulations:
        formulation.slug = slugify(formulation.name)
        formulation.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("dashboard", "0040_tracingformulations_slug")]

    operations = [migrations.RunPython(update_slugs, reverse)]
