# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-31 21:21
from __future__ import unicode_literals

from django.db import migrations

from django.db import migrations
from pydash import slugify

MODEL = "model"

PATIENT_FORMULATIONS = "patient_formulations"
CONSUMPTION_FORMULATIONS = "consumption_formulations"

NAME = "name"

F3_PATIENT_QUERY = ["ABC/3TC/EFV", "AZT/3TC/EFV"]

F2_PATIENT_QUERY = ["ABC/3TC/LPV/r", "ABC/3TC/EFV", "ABC/3TC/NVP"]
F3 = "EFV200 (Paed)"
F2 = "ABC/3TC (Paed)"
F1 = "TDF/3TC/EFV (Adult)"
F1_PATIENT_QUERY = ["TDF/3TC/EFV (PMTCT)", "TDF/3TC/EFV (ADULT)"]
F1_QUERY = ["Tenofovir/Lamivudine/Efavirenz (TDF/3TC/EFV) 300mg/300mg/600mg[Pack 30]"]
F3_QUERY = ["Efavirenz (EFV) 200mg [Pack 90]"]
F2_QUERY = ["Abacavir/Lamivudine (ABC/3TC) 60mg/30mg [Pack 60]"]


def add_default_tracers(apps, schema_editor):
    model = apps.get_registered_model("dashboard", "TracingFormulations")
    tracers = [
        {NAME: F1, PATIENT_FORMULATIONS: F1_PATIENT_QUERY, CONSUMPTION_FORMULATIONS: F1_QUERY, "slug": slugify(F1)},
        {NAME: F2, PATIENT_FORMULATIONS: F2_PATIENT_QUERY, CONSUMPTION_FORMULATIONS: F2_QUERY, "slug": slugify(F2)},
        {NAME: F3, PATIENT_FORMULATIONS: F3_PATIENT_QUERY, CONSUMPTION_FORMULATIONS: F3_QUERY, "slug": slugify(F3)}, ]
    model.objects.all().delete()
    for tracer in tracers:
        model_obj, created = model.objects.get_or_create(**tracer)
        model_obj.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0043_remove_tracingformulations_model'),
    ]

    operations = [
        migrations.RunPython(add_default_tracers, reverse),
    ]
