# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-31 23:09
from __future__ import unicode_literals

import json

from django.db import migrations

from dashboard.checks.builder import class_based_check, guideline_adherence_adult1l_check, \
    guideline_adherence_adult2l_check, guideline_paed1l_check, no_negatives_check, volume_tally_check, \
    non_repeating_check, open_closing_check, stable_consumption_check, nnrti_paed, warehouse_fulfillment_check, \
    nnrti_adult


def create_default_tests(apps, schema_editor):
    pass


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0044_cleanup_tracing_formulations'),
    ]

    operations = [
        migrations.RunPython(create_default_tests, reverse),
    ]
