# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-29 23:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_add-missing-tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='state',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='facilitytest',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='locationtopartnermapping',
            name='mapping',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
