# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20151126_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='locations.IP'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='locations.WareHouse'),
        ),
    ]
